### PR TITLE
RSpec 3 & fix deprecations; bump v0.1.3

### LINKED ISSUE #9: Bump new version to rubygems?
Hi 

I'd like to bump a new version of this code to rubygems to access the `signal` method in order to change IP address. Any chance we could do this? Im happy to help.

### PR DESCRIPTION
**Pull request by MatzFan**
Old exit node IP & deprecated RSpec 2 syntax broke 3 tests.

Bumped to new version to fix #9 (once pushed to Rubygems).

### CODE REVIEW

**Comment by wieczorek1990** [comment]
Guys why is this IP changed everywhere?

**Comment by wieczorek1990** [comment]
Looks fine.

**Comment by MatzFan** [comment]
Thanks. Looking forward to seeing 0.1.3 at https://rubygems.org/gems/tor.

**Comment by wieczorek1990** [comment]
@artob Can you please push the gem to rubygems?

**Comment by artob** [comment]
@wieczorek1990 I'm not set up with a Ruby toolchain at the moment. I've added you as a gem owner at RubyGems, so that you are able to push new versions.

**Comment by wieczorek1990** [comment]
@artob I'm not wieczorek1990 on rubygems, please add lwieczorek.

**Comment by artob** [comment]
@wieczorek1990 Now corrected!

**Comment by wieczorek1990** [comment]
Pushed. https://rubygems.org/gems/tor

**Comment by wieczorek1990** [comment]
@artob Turns out I'm wieczorek1990 on rubygems too but on an old email, please change from lwieczorek to wieczorek1990.

**Comment by artob** [comment]
@wieczorek1990 Added.

**Pull request merged**
